name: ink_scratch
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.7
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/content.png
    - assets/icons/miku.jpg